=== Ser87ch/Support/xml/settings/general.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:documentation>Общие настройки для тестов
		</xs:documentation>
	</xs:annotation>
	<xs:element name="general">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="server" type="xs:string">
					<xs:annotation>
						<xs:documentation>Сервер</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="db" type="xs:string">
					<xs:annotation>
						<xs:documentation>База данных</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="user" type="xs:string">
					<xs:annotation>
						<xs:documentation>Пользователь</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="pwd" type="xs:string">
					<xs:annotation>
						<xs:documentation>Пароль</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="path" type="xs:string">
					<xs:annotation>
						<xs:documentation>Путь к САБС</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="bik">
					<xs:annotation>
						<xs:documentation>БИК</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:length value="9" />
					</xs:restriction>
				</xs:simpleType>
				</xs:element>
				<xs:element name="operdate" type="xs:date">
					<xs:annotation>
						<xs:documentation>Опер день</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="testproj" type="xs:string">
					<xs:annotation>
						<xs:documentation>Путь к проекту</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="folder" type="xs:string">
					<xs:annotation>
						<xs:documentation>Папка текущего теста</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="fullfolder" type="xs:string">
					<xs:annotation>
						<xs:documentation>Полный путь к папке текущего теста</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="datafolder" type="xs:string">
					<xs:annotation>
						<xs:documentation>Полный путь к папке текущих данных</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Ser87ch/Support/xml/settings/general.xml
<?xml version="1.0" encoding="UTF-8"?>
<general xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="general.xsd">
	<server>CHERNOBRIVENKO\\ATLANT:1259</server>
	<db>sabs_zapd</db>
	<user>robot</user>
	<pwd>1</pwd>
	<path>D:\aspu\sabs_zapd2000</path>
	<bik>044582002</bik>
	<operdate>2011-09-07</operdate>
	<testproj>G:\sabstest\</testproj>
	<folder>a000001</folder>
	<fullfolder>G:\sabstest\tests\a000001\</fullfolder>
</general>
